environment:
  PYTHONIOENCODING: "utf8:backslashreplace"
  PYTHONLEGACYWINDOWSSTDIO: "1"
  matrix:
    - PYTHON: "C:\\Python35"
    - PYTHON: "C:\\Python35-x64"
    - PYTHON: "C:\\Python36"
    - PYTHON: "C:\\Python36-x64"
    - PYTHON: "C:\\Python37"
    - PYTHON: "C:\\Python37-x64"
  MAKE: C:\MinGW\bin\mingw32-make.exe
  TWINE_USERNAME: __token__
  TWINE_PASSWORD:
    secure: 4oGYDgM9gfndCpp+Fk3AwTw7KtULlx2iOQcJ8/k/t1SUW2l0UkK4WbZNUMFtkAeT3mv1ibSKI0BuuYUUjtSJPF1mSki+Ky1nSaaLj22B5Dp4XLOOGJQKQtBXMkjc6g3A3O1GjzBDfzhXlfs961ETtHE2x+3z9jbIpTYzL6HxUL6EVthyA1OPVbZ65bwvoQhRC1AaFx4Qrr6ToZ5el5PUT/XWPJpj3RnMYTz64mmu/FrpCElDqDAtGib3P5WeZ+DqIQHmiw0DdqeeVN3ZQmlx7g==

cache:
  - '%LOCALAPPDATA%\pip\Cache'

init:
  - "chcp 65001"
  - ps: >-
      if($env:APPVEYOR_RDP_DEBUG -eq 'True') {
        iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
      }

install:
  - >-
    tools/build.cmd %PYTHON%\python.exe -m
    pip install -U pip wheel setuptools
  - '%MAKE% cythonize'
  - "tools/build.cmd %PYTHON%\\python.exe -m pip install -r requirements/ci.txt"

build_script:
  - "tools/build.cmd %PYTHON%\\python.exe -m setup sdist bdist_wheel"

test_script:
  - "tools/build.cmd %PYTHON%\\python.exe -m pytest -c pytest.ci.ini --cov-report xml"

after_test:
  - "tools/build.cmd %PYTHON%\\python.exe -m codecov -f coverage.xml -X gcov"

artifacts:
  - path: dist\*

deploy_script:
  - ps: >-
      if($env:appveyor_repo_tag -eq 'True') {
          Invoke-Expression "$env:PYTHON\\python.exe -m twine upload dist/* --skip-existing"
      }

on_finish:
  - ps: >-
      if($env:APPVEYOR_RDP_DEBUG -eq 'True') {
        $blockRdp = $true
        iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
      }

#notifications:
#  - provider: Webhook
#    url: https://ci.appveyor.com/api/github/webhook?id=08c7793w1tp839fl
#    on_build_success: false
#    on_build_failure: True
