conditions: v1
version: "= 0"
if: >  # Forbid running non-PR pushes from pyup bot
  not (type != pull_request AND branch =~ ^pyup\-scheduled\-update\-)

dist: xenial

language: python

python:
- 3.5
- 3.6
- &mainstream_python 3.7
- 3.8-dev
- &pypy3 pypy3.5-6.0.0

install:
- &upgrade_python_toolset pip install --upgrade pip wheel setuptools
- make cythonize
- pip install -r requirements/ci.txt

script:
- make cov-ci-run

after_success:
 - codecov

_helpers:
- &_mainstream_python_base
  python: *mainstream_python
- &_reset_steps
  env: []
  before_install: skip
  install: skip
  script: skip
  after_success: []
- &_lint_base
  stage: &doc_stage_name docs, linting and pre-test checks
  <<: *_mainstream_python_base
  <<: *_reset_steps
  install:
  - *upgrade_python_toolset
  - pip install -U -r requirements/ci.txt
- &_doc_base
  <<: *_lint_base
  install:
  - *upgrade_python_toolset
  - pip install -U -r requirements/doc.txt -r requirements/doc-spelling.txt
  after_failure: cat docs/_build/spelling/output.txt
  addons:
    apt:
      packages:
      - libenchant-dev
- &osx_python_base
  stage: &stage_test_osx_name test under OS X (last chance to fail before deploy available)
  os: osx
  language: shell
  python: *pypy3
  env:
  - &env_pypy3 PYTHON_VERSION=pypy3.6-7.1.1
  - &env_pyenv PYENV_ROOT="$HOME/.pyenv"
  - &env_path PATH="$PYENV_ROOT/bin:$PATH"
  before_install:
  - brew update
  - brew install pyenv || brew upgrade pyenv
  - &ensure_pyenv_preloaded |
    eval "$(pyenv init -)"
    eval "$(pyenv virtualenv-init -)"
  - &install_python pyenv install --skip-existing --keep --verbose "$PYTHON_VERSION"
  - &switch_python pyenv shell "$PYTHON_VERSION"
  - &python_version python --version
  before_cache:
  - brew --cache
- &generic_deploy_base
  stage: &deploy_stage_name deploy (PYPI upload itself runs only for tagged commits)
  <<: *_mainstream_python_base
  deploy: &deploy_step
    provider: pypi
    # `skip_cleanup: true` is required to preserve binary wheels, built
    # inside of manylinux1 docker container during `script` step above.
    skip_cleanup: true
    # `skip-existing: true` is required to skip uploading dists, already
    # present in PYPI instead of failing the whole process.
    # This happens when other CI (AppVeyor etc.) has already uploaded
    # the very same dist (usually sdist).
    skip_existing: true
    username: __token__
    password:
      # Encrypted with `travis encrypt`:
      secure: "Ja3wInSJu161pf9yHxDhthYknOQLM3unzGNU7oMkVcZkt9HahTjQAQy6TV7ELfe18nYj0hNBGVbbEE4tPtf8ENtcjfU5HVxrqaLSKq/A361HfrXUiXJhq1INaf3ZBDA7kxLo9CWlWYoy0UWDgzZhkGEwjvBbLV8/6D3+5cJqzmORl3so8RHp7iJDjlL4aKc8DTwKdeBFLi0QhtA7kWUzOFUlQal5q4qDhdC3xil0m8LgvszQwYB9MuChw/qN/Y+uQ6L/ANMoZLl0Pdl6MdWtak8Tqu/a+AZMft+mjX5AzYbCBkDgsvvzIZi8GOZ0tNYpGsspwOk6xE9Auwvtdm8NXwEJ7ea8TJSiot3OuYIs9FXzmTjhtAZ11TC4UQ3krJQdZ4BmbW73CGxQuAQqe/QZBcCR6i1a1RbAXSoqqC7rfmKNHKPcPQHGsRdV5bGIMdRR+XVvizW+v8CSJU2d6rs+WqysyxQbipi6ASNeLfHO2zOgHREPQfwn2AE0PeNfN3if67SaC2uEQGc4qnkWs7gDhWZro1zBXsy7G8aKmCalE6RqcQT5JqjqJqSYWKHTUVVg2xVQTMajhYmqkvbaIgjCr0YHlLGcficLAg7r+8dJVKLyzQ13/TFh5fm2FPHFGQLNua/ZraPGSWRCOKuTKeMxvyMY4JqSQ8KB22TnYhx2yy8="
    # Although Travis CI instructs `setup.py` to build source distribution,
    # which is default value for distribution option (`distribution: sdist`),
    # it will also upload all wheels we've previously built in manylinux1
    # docker container using `twine upload -r pypi dist/*` command.
    # Also since commit https://github.com/travis-ci/dpl/commit/90b5e39
    # it is default that Travis PYPI provider has `skip_upload_docs: true`
    # set by default.
    # Besides above, we don't do cleanup of `dist/*`, because it's being done
    # by Travis CI PYPI deployment provider after upload, unconditionally.
    on:
      tags: true
      all_branches: true
- &osx_pypi_deploy_base_1011
  <<: *osx_python_base
  <<: *generic_deploy_base
  osx_image: xcode7.3
  script: skip
  after_success: []
  env:
  - &env_os1011_msg Build and deploy to PYPI of OS X 10.11 binary wheel=
  - &env_py36 PYTHON_VERSION=3.6.3
  - *env_pyenv
  - *env_path
  deploy:
    <<: *deploy_step
    skip_cleanup: false
    distributions: bdist_wheel
- &osx_pypi_deploy_base_1012
  <<: *osx_pypi_deploy_base_1011
  osx_image: xcode8.1
  env:
  - &env_os1012_msg Build and deploy to PYPI of OS X 10.12 binary wheel=
  - *env_py36
  - *env_pyenv
  - *env_path
- &osx_pypi_deploy_base_1010
  <<: *osx_pypi_deploy_base_1011
  osx_image: xcode6.4
  env:
  - &env_os1010_msg Build and deploy to PYPI of OS X 10.10 binary wheel=
  - *env_py36
  - *env_pyenv
  - *env_path


os: linux

matrix:
  fast_finish: true
  allow_failures:
  - python: 3.8-dev

  include:
  - name: 3.7 without extensions
    python: 3.7
    env:
      FROZENLIST_NO_EXTENSIONS: "1"

  - <<: *_doc_base
    name: Checking docs spelling
    script:
    - make doc-spelling

  - <<: *_doc_base
    name: Checking Towncrier fragments
    install:
    - *upgrade_python_toolset
    - pip install -r requirements/cython.txt
    - FROZENLIST_NO_EXTENSIONS=1 pip install -r requirements/ci.txt
    - pip install -r requirements/towncrier.txt
    script:
    - towncrier --yes

  - <<: *_lint_base
    name: Linting source code with flake8
    install:
    - *upgrade_python_toolset
    - pip install -r requirements/flake.txt
    script:
    - flake8 frozenlist tests

  - <<: *_lint_base
    name: Linting source code with mypy
    install:
    - *upgrade_python_toolset
    - pip install -r requirements/cython.txt
    - FROZENLIST_NO_EXTENSIONS=1 pip install -r requirements/ci.txt
    script:
    - mypy frozenlist

  - <<: *_lint_base
    name: Verifying distribution package metadata
    install:
    - *upgrade_python_toolset
    - FROZENLIST_NO_EXTENSIONS=1 pip install -r requirements/ci.txt -r requirements/doc.txt
    script:
    - FROZENLIST_NO_EXTENSIONS=1 python setup.py --verbose sdist bdist_wheel
    - twine check dist/*

  - <<: *_lint_base
    name: Making sure that CONTRIBUTORS.txt remains sorted
    language: shell
    install:
    - skip
    script:
    - LC_ALL=C sort -c CONTRIBUTORS.txt

  - <<: *osx_python_base
    python: 3.5.3
    env:
    - &env_py35 PYTHON_VERSION=3.5.3
    - *env_pyenv
    - *env_path
  - <<: *osx_python_base
    python: *mainstream_python
    env:
    - *env_py36
    - *env_pyenv
    - *env_path
  - <<: *osx_python_base
    python: 3.7
    env:
    - &env_py37 PYTHON_VERSION=3.7.0
    - *env_pyenv
    - *env_path
  # pypy3.5-5.10.0 fails under OS X because it's unsupported

  # Build and deploy manylinux1 binary wheels and source distribution
  - <<: *generic_deploy_base
    <<: *_reset_steps
    env: Build and deploy to PYPI of manylinux1 binary wheels for all supported Pythons and source distribution=
    services:
    - docker
    script:
    - pip install -r requirements/cython.txt
    - pip install -r requirements/ci.txt  # to compile *.c files by Cython
    - make cythonize
    - ./tools/run_docker.sh "frozenlist"
    deploy:
      <<: *deploy_step

    # Build and deploy MacOS binary wheels for each OSX+Python combo possible
    # OS X 10.10, Python 3.5
  - <<: *osx_pypi_deploy_base_1010
    python: 3.5
    env:
    - *env_os1010_msg
    - *env_py35
    - *env_pyenv
    - *env_path
    # OS X 10.10, Python 3.6
  - <<: *osx_pypi_deploy_base_1010
    env:
    - *env_os1010_msg
    - *env_py36
    - *env_pyenv
    - *env_path
    # OS X 10.10, Python 3.7
  - <<: *osx_pypi_deploy_base_1010
    env:
    - *env_os1010_msg
    - *env_py37
    - *env_pyenv
    - *env_path
    # OS X 10.11, Python 3.5
  - <<: *osx_pypi_deploy_base_1011
    python: 3.5
    env:
    - *env_os1011_msg
    - *env_py35
    - *env_pyenv
    - *env_path
    # OS X 10.11, Python 3.6
  - <<: *osx_pypi_deploy_base_1011
    env:
    - *env_os1011_msg
    - *env_py36
    - *env_pyenv
    - *env_path
    # OS X 10.11, Python 3.7
  - <<: *osx_pypi_deploy_base_1011
    env:
    - *env_os1011_msg
    - *env_py37
    - *env_pyenv
    - *env_path
    # OS X 10.12, Python 3.5
  - <<: *osx_pypi_deploy_base_1012
    python: 3.5
    env:
    - *env_os1012_msg
    - *env_py35
    - *env_pyenv
    - *env_path
    # OS X 10.12, Python 3.6
  - <<: *osx_pypi_deploy_base_1012
    env:
    - *env_os1012_msg
    - *env_py36
    - *env_pyenv
    - *env_path
    # OS X 10.12, Python 3.7
  - <<: *osx_pypi_deploy_base_1012
    env:
    - *env_os1012_msg
    - *env_py37
    - *env_pyenv
    - *env_path

stages:
- *doc_stage_name
- test
- name: *stage_test_osx_name
  if: type IN (api, cron)
- name: *deploy_stage_name
  # This will prevent deploy unless it's a tagged commit:
  if: tag IS present


cache: pip

before_cache:
- rm -f $HOME/.cache/pip/log/debug.log
