parameters:
  ignoreFailed: false

steps:
- checkout: self
  clean: true
  submodules: true

- task: UsePythonVersion@0
  name: UsePythonVersion
  continueOnError: true
  inputs:
    versionSpec: '$(python.version)'
    architecture: 'x64'

- script: |
    env
    echo "Failing job because $PYTHON_VERSION is not available"
    echo "##vso[task.setvariable variable=Agent.JobStatus;]Failed"
    exit 1
  condition: and(not(variables['UsePythonVersion.pythonLocation']), ${{ parameters.ignoreFailed }})
  displayName: 'Fail for missing python version'

- script: |
    python -m pip install --upgrade pip setuptools
  condition: and(succeeded(), variables['UsePythonVersion.pythonLocation'])
  displayName: 'Update pip'

- script: |
    make cythonize
  condition: and(succeeded(), variables['UsePythonVersion.pythonLocation'], eq(variables['no_extensions'], ''))
  displayName: 'Cythonize'

- script: |
    pip install -r requirements/dev.txt pytest-azurepipelines
  displayName: 'Install dependencies'
  condition: and(succeeded(), variables['UsePythonVersion.pythonLocation'])
  env:
    FROZENLIST_NO_EXTENSIONS: '$(no_extensions)'

- script: |
    pytest tests -vv --no-coverage-upload
  condition: and(succeeded(), variables['UsePythonVersion.pythonLocation'])
  displayName: 'pytest'

- script: |
    python -m coverage xml
  displayName: 'Prepare coverage'
  condition: and(succeeded(), variables.py.pythonLocation)

- script: |
    pip install codecov
    python -m codecov -f coverage.xml -X gcov
  displayName: 'Upload coverage reports'
  condition: and(succeeded(), variables.py.pythonLocation, ne(variables['codecov.token'], ''))
  env:
    CODECOV_TOKEN: $(codecov.token)
