steps:
- checkout: self
  clean: true
  submodules: true

- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
    architecture: 'x64'

- script: |
    python -m pip install --upgrade pip setuptools
  displayName: 'Update pip'

- script: |
    make cythonize
  condition: and(succeeded(), eq(variables['no_extensions'], ''))
  displayName: 'Cythonize'

- script: |
    pip install -r requirements/dev.txt pytest-azurepipelines
  displayName: 'Install dependencies'
  env:
    FROZENLIST_NO_EXTENSIONS: '$(no_extensions)'

- script: |
    pytest tests -vv --no-coverage-upload
  displayName: 'pytest'

- script: |
    python -m coverage xml
  displayName: 'Prepare coverage'

- script: |
    pip install codecov
    python -m codecov -f coverage.xml -X gcov
  displayName: 'Upload coverage reports'
  condition: and(succeeded(), ne(variables['codecov.token'], ''))
  env:
    CODECOV_TOKEN: $(codecov.token)
