trigger:
  batch: true
  branches:
    include:
    - master
    - azure-pipelines
  tags:
    exclude:
    - '*'
pr:
  autoCancel: true
  branches:
    include:
    - master

variables:
- group: codecov

stages:
# - template: templates/stage-lint.yml
- template: templates/stage-test.yml
  parameters:
    pythonVersions:
      - '3.6'
      - '3.7'
      - '3.8'

