trigger:
  tags:
    include:
    - v?.*
pr: none


variables:
- group: codecov
- group: twine


resources:
  containers:
  - container: manylinux
    image: quay.io/pypa/manylinux1_x86_64
  repositories:
  - repository: templates
    type: github
    name: mjpieters/azure-pipelines
    endpoint: mjpieters

stages:
- template: stage-lint.yml

- template: stage-test.yml

- template: stage-deploy.yml
  parameters:
    pythonVersions:
      - '3.6'
      - '3.7'
      # - '3.8' when properly rolled out on the Azure fleet.

- template: templates/stage-publish.yml@templates
  parameters:
    github: release-upload
