parameters:
  toleratePythonMissing: false

steps:
- checkout: self
  clean: true

- task: UsePythonVersion@0
  ${{ if parameters.toleratePythonMissing }}:
    continueOnError: true
  inputs:
    versionSpec: '$(python.version)'
    architecture: 'x64'

- script: |
    python -m pip install --upgrade pip setuptools
  condition: and(succeeded(), variables['UsePythonVersion.pythonLocation'])
  displayName: 'Update pip'

- script: |
    make cythonize
  condition: and(variables['no_extensions'], succeeded(), variables['UsePythonVersion.pythonLocation'])
  displayName: 'Cythonize'

- script: |
    pip install -r requirements/dev.txt pytest-azurepipelines
  env:
    ${{ if variables['no_extensions'] }}:
      FROZENLIST_NO_EXTENSIONS: 'Y'
  condition: and(succeeded(), variables['UsePythonVersion.pythonLocation'])
  displayName: 'Install dependencies'


- script: |
    pytest tests -vv --no-coverage-upload
  condition: and(succeeded(), variables['UsePythonVersion.pythonLocation'])
  displayName: 'pytest'

- script: |
    python -m coverage xml
  displayName: 'Prepare coverage'
  condition: and(succeeded(), variables['UsePythonVersion.pythonLocation'])

- script: |
    pip install codecov
    python -m codecov -f coverage.xml -X gcov
  env:
    CODECOV_TOKEN: $(codecov.token)
  condition: and(variables['codecov.token'], succeeded(), variables['UsePythonVersion.pythonLocation'])
  displayName: 'Upload coverage reports'
